# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tejas Jadhav
title: Systems Engineer
email: Tejas.jadhav@aggiemail.usu.edu
website: 

# Social links
#twitter_username: facespics
github_username:  tejaas123
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects:
Projects: | 
Validation for all things related to media within the Volkswagen Group.

# Experience Section
experience_title: Experience
Been with the VWGoA since March 2014.
# Education Section
educaton_title: Education
Utah State University alumni.

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Road biking
   - Bibliophism
   - Cooking
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
